# -*- coding: utf-8 -*-
"""
Created on Mon Jan  5 16:31:43 2026

@author: Chen-Lab
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import umap
import os

# ==========================================
# 1. FILE PATHS
# ==========================================
# The embedding files generated by your feature extraction script
path_indices = r"D:/SynapseCLR/output/checkpoint_synapseclr_so3_seed_44_first_stage/features/extracted_features__node.0__epoch.99__index_array.npy"
path_embeddings = r"D:/SynapseCLR/output/checkpoint_synapseclr_so3_seed_44_first_stage/features/extracted_features__node.0__epoch.99__projector.mlp.0.npy"

# The original metadata used by the model (used to align indices)
path_meta_master = r"D:/SynapseCLR/data/processed/meta.csv"

# Your new CSV containing the 1/0 ground truth labels
path_labels = r"D:/SynapseCLR/data/processed/meta_cell_info.csv"

# ==========================================
# 2. LOAD AND ALIGN DATA
# ==========================================
print("Loading data...")
indices = np.load(path_indices)
embeddings = np.load(path_embeddings)

# Load the master metadata to handle the indexing
df_master = pd.read_csv(path_meta_master)

# Check if indices are valid for the master file
if indices.max() >= len(df_master):
    raise ValueError(f"Max index ({indices.max()}) exceeds Master CSV rows ({len(df_master)}). "
                     "Ensure path_meta_master points to the full dataset.")

# Align the master dataframe to the embeddings
df_aligned = df_master.iloc[indices].copy().reset_index(drop=True)

# Load your custom labels and merge them based on synapse_id
df_info = pd.read_csv(path_labels)
df_aligned = pd.merge(
    df_aligned, 
    df_info[['synapse_id', 'pre_cell_type', 'post_cell_type']], 
    on='synapse_id', 
    how='left'
)

print(f"Aligned {len(df_aligned)} rows.")
print(f"Labeled synapses found: {df_aligned['pre_cell_type'].notna().sum()}")

# ==========================================
# 3. FEATURE ENGINEERING
# ==========================================
print("Categorizing Excitatory/Inhibitory pairs...")

def define_synapse_type(row):
    """
    Determines the synapse pair type based on 1 (Exc) and 0 (Inh).
    """
    col_pre = 'pre_cell_type'  
    col_post = 'post_cell_type'
    
    # Check if columns exist or are NaN
    if pd.isna(row[col_pre]) or pd.isna(row[col_post]):
        return "Unknown"

    # Mapping logic: 1 -> Exc, 0 -> Inh
    mapping = {1: 'Exc', 0: 'Inh', 1.0: 'Exc', 0.0: 'Inh'}

    type_pre = mapping.get(row[col_pre], 'Unknown')
    type_post = mapping.get(row[col_post], 'Unknown')

    if type_pre == 'Unknown' or type_post == 'Unknown':
        return 'Unknown'
    
    return f"{type_pre} -> {type_post}"

# Apply the function row-by-row
df_aligned['synapse_pair'] = df_aligned.apply(define_synapse_type, axis=1)

# ==========================================
# 4. DIMENSIONALITY REDUCTION (UMAP)
# ==========================================
print("Running UMAP (this may take a moment)...")
reducer = umap.UMAP(n_neighbors=30, min_dist=0.1, metric='cosine', random_state=42)
embedding_2d = reducer.fit_transform(embeddings)

df_aligned['umap_x'] = embedding_2d[:, 0]
df_aligned['umap_y'] = embedding_2d[:, 1]

# ==========================================
# 5. PLOTTING
# ==========================================
print("Generating plot...")
plt.style.use('dark_background')
plt.figure(figsize=(12, 10))

# We include 'Unknown' in the plot so we can see all synapses,
# but we give them a neutral color.
custom_palette = {
    'Exc -> Exc': '#00FF00', # Lime Green
    'Exc -> Inh': '#FF0000', # Red
    'Inh -> Exc': '#00FFFF', # Cyan
    'Inh -> Inh': '#FF00FF', # Magenta
    'Unknown': '#444444'     # Grey
}

sns.scatterplot(
    data=df_aligned,
    x='umap_x',
    y='umap_y',
    hue='synapse_pair',
    palette=custom_palette,
    s=30,
    alpha=0.7,
    edgecolor='w',
    linewidth=0.5
)

plt.title("SynapseCLR Embeddings: Ground Truth Connectivity Motifs", fontsize=14)
plt.legend(bbox_to_anchor=(1.02, 1), loc='upper left', title="Synapse Type")
plt.xlabel("UMAP Dimension 1")
plt.ylabel("UMAP Dimension 2")
plt.tight_layout()

plt.show()
